dropped unneccessary column

In [1]:
from sklearn.impute import KNNImputer
import pandas as pd
df=pd.read_csv('/content/west_coast dataset.csv')
df.shape


df.sample(5)

<ipython-input-1-1e457763e49d>:3: DtypeWarning: Columns (0,2,22,41,45,46,54,61) have mixed types. Specify dtype option on import or set low_memory=False.
  df=pd.read_csv('/content/west_coast dataset.csv')

,id,listing_url,scrape_id,last_scraped,source,name,description,neighborhood_overview,picture_url,host_id,...,review_scores_location,review_scores_value,license,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month,city
388,53047412,https://www.airbnb.com/rooms/53047412,20240904164210,2024-09-05,city scrape,The Artist Loft - 1250sqft (1 MONTH MIN),Welcome to this large open floor plan architec...,Experience the vibrant Marina Arts District – ...,https://a0.muscache.com/pictures/e55396a9-87e6...,57038004.0,...,5.00,4.75,NaN,f,2.0,2.0,0.0,0.0,0.12,los_angeles
4199,37240303,https://www.airbnb.com/rooms/37240303,20240904164210,2024-09-04,city scrape,"Heartwell Studio - Park View, Peaceful + Private",Located in a charming neighborhood with a full...,- Historic Heartwell Park a few steps from the...,https://a0.muscache.com/pictures/b939f5df-c5d5...,26450709.0,...,4.95,4.94,PRP21-00001,f,1.0,1.0,0.0,0.0,1.54,los_angeles
6580,1131473027888978717,https://www.airbnb.com/rooms/1131473027888978717,20240904163718,2024-09-04,city scrape,Cozy Hilltop California Bungalow Retreat,Centrally located at the intersection of Noe V...,NaN,https://a0.muscache.com/pictures/hosting/Hosti...,46968764.0,...,5.00,5.00,2024-003186STR,f,1.0,1.0,0.0,0.0,0.81,san_francisco
180,15070636,https://www.airbnb.com/rooms/15070636,20240904164210,2024-09-05,previous scrape,Historic Theatre Converted into Artistic Abode,"Famously rented by Katy Perry, Kelly Rowland, ...",This completely re-imagined estate retains ori...,https://a0.muscache.com/pictures/monet/Select-...,9862811.0,...,4.77,4.88,HSR22-003887,f,6.0,6.0,0.0,0.0,1.03,los_angeles
8858,36199745,https://www.airbnb.com/rooms/36199745,20240904164328,2024-09-04,previous scrape,"Hotel Rose, Cityscape King",The illuminating lights of the Hotel Rose neon...,NaN,https://a0.muscache.com/pictures/5334fc36-03f2...,270114277.0,...,4.61,4.48,39040,t,12.0,0.0,12.0,0.0,5.77,portland

checking for duplicates

In [2]:
print(len(df)-len(df.drop_duplicates()))
#dropping unneccessary column
columns_to_drop = ['calendar_updated','listing_url','scrape_id','source','picture_url','host_id','host_url','host_thumbnail_url','host_picture_url','neighbourhood']
df = df.drop(columns=columns_to_drop, errors='ignore')
df.shape
df.info()

0
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10002 entries, 0 to 10001
Data columns (total 66 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   id                                            10002 non-null  object
 1   last_scraped                                  10002 non-null  object
 2   name                                          10002 non-null  object
 3   description                                   9718 non-null   object
 4   neighborhood_overview                         5825 non-null   object
 5   host_name                                     10002 non-null  object
 6   host_since                                    10002 non-null  object
 7   host_location                                 7842 non-null   object
 8   host_about                                    5865 non-null   object
 9   host_response_time                            8422 non-null   object
 10  host_response_rate                            8422 non-null   object
 11  host_acceptance_rate                          8530 non-null   object
 12  host_is_superhost                             9732 non-null   object
 13  host_neighbourhood                            8454 non-null   object
 14  host_listings_count                           10000 non-null  object
 15  host_total_listings_count                     10000 non-null  float64
 16  host_verifications                            9999 non-null   object
 17  host_has_profile_pic                          10000 non-null  object
 18  host_identity_verified                        9999 non-null   object
 19  neighbourhood_cleansed                        10000 non-null  object
 20  neighbourhood_group_cleansed                  5726 non-null   object
 21  latitude                                      10000 non-null  float64
 22  longitude                                     10000 non-null  float64
 23  property_type                                 10000 non-null  object
 24  room_type                                     10000 non-null  object
 25  accommodates                                  10000 non-null  float64
 26  bathrooms                                     8599 non-null   float64
 27  bathrooms_text                                9995 non-null   object
 28  bedrooms                                      9538 non-null   float64
 29  beds                                          8578 non-null   float64
 30  amenities                                     10000 non-null  object
 31  price                                         8601 non-null   object
 32  minimum_nights                                10000 non-null  object
 33  maximum_nights                                10000 non-null  float64
 34  minimum_minimum_nights                        10000 non-null  float64
 35  maximum_minimum_nights                        10000 non-null  float64
 36  minimum_maximum_nights                        10000 non-null  object
 37  maximum_maximum_nights                        10000 non-null  object
 38  minimum_nights_avg_ntm                        10000 non-null  float64
 39  maximum_nights_avg_ntm                        10000 non-null  float64
 40  has_availability                              9557 non-null   object
 41  availability_30                               10000 non-null  float64
 42  availability_60                               10000 non-null  float64
 43  availability_90                               10000 non-null  float64
 44  availability_365                              10000 non-null  object
 45  calendar_last_scraped                         10000 non-null  object
 46  number_of_reviews                             10000 non-null  float64
 47  number_of_reviews_ltm                         10000 non-null  float64
 48  number_of_reviews_l30d                        10000 non-null  float64
 49  first_review                                  7808 non-null   object
 50  last_review                                   7808 non-null   object
 51  review_scores_rating                          7808 non-null   object
 52  review_scores_accuracy                        7796 non-null   float64
 53  review_scores_cleanliness                     7796 non-null   float64
 54  review_scores_checkin                         7794 non-null   float64
 55  review_scores_communication                   7796 non-null   float64
 56  review_scores_location                        7795 non-null   float64
 57  review_scores_value                           7795 non-null   float64
 58  license                                       4126 non-null   object
 59  instant_bookable                              9998 non-null   object
 60  calculated_host_listings_count                9998 non-null   float64
 61  calculated_host_listings_count_entire_homes   9998 non-null   float64
 62  calculated_host_listings_count_private_rooms  9998 non-null   float64
 63  calculated_host_listings_count_shared_rooms   9998 non-null   float64
 64  reviews_per_month                             7806 non-null   float64
 65  city                                          9998 non-null   object
dtypes: float64(29), object(37)
memory usage: 5.0+ MB

In [4]:
#calculate the percentage of missing value
round(df.isnull().sum()/len(df)*100,2).sort_values(ascending=False)

license                         58.75
neighbourhood_group_cleansed    42.75
neighborhood_overview           41.76
host_about                      41.36
review_scores_checkin           22.08
                                ...
last_scraped                     0.00
host_since                       0.00
host_name                        0.00
name                             0.00
id                               0.00
Length: 66, dtype: float64

From this I can see that license,neighbourhood_group_cleansed,neighbourhood_overview,host_about

so dropping those column as well

In [5]:
column_with_large_missing_values=['license','neighbourhood_group_cleansed','neighborhood_overview','host_about']
df=df.drop(columns=column_with_large_missing_values,errors='ignore')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10002 entries, 0 to 10001
Data columns (total 62 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   id                                            10002 non-null  object
 1   last_scraped                                  10002 non-null  object
 2   name                                          10002 non-null  object
 3   description                                   9718 non-null   object
 4   host_name                                     10002 non-null  object
 5   host_since                                    10002 non-null  object
 6   host_location                                 7842 non-null   object
 7   host_response_time                            8422 non-null   object
 8   host_response_rate                            8422 non-null   object
 9   host_acceptance_rate                          8530 non-null   object
 10  host_is_superhost                             9732 non-null   object
 11  host_neighbourhood                            8454 non-null   object
 12  host_listings_count                           10000 non-null  object
 13  host_total_listings_count                     10000 non-null  float64
 14  host_verifications                            9999 non-null   object
 15  host_has_profile_pic                          10000 non-null  object
 16  host_identity_verified                        9999 non-null   object
 17  neighbourhood_cleansed                        10000 non-null  object
 18  latitude                                      10000 non-null  float64
 19  longitude                                     10000 non-null  float64
 20  property_type                                 10000 non-null  object
 21  room_type                                     10000 non-null  object
 22  accommodates                                  10000 non-null  float64
 23  bathrooms                                     8599 non-null   float64
 24  bathrooms_text                                9995 non-null   object
 25  bedrooms                                      9538 non-null   float64
 26  beds                                          8578 non-null   float64
 27  amenities                                     10000 non-null  object
 28  price                                         8601 non-null   object
 29  minimum_nights                                10000 non-null  object
 30  maximum_nights                                10000 non-null  float64
 31  minimum_minimum_nights                        10000 non-null  float64
 32  maximum_minimum_nights                        10000 non-null  float64
 33  minimum_maximum_nights                        10000 non-null  object
 34  maximum_maximum_nights                        10000 non-null  object
 35  minimum_nights_avg_ntm                        10000 non-null  float64
 36  maximum_nights_avg_ntm                        10000 non-null  float64
 37  has_availability                              9557 non-null   object
 38  availability_30                               10000 non-null  float64
 39  availability_60                               10000 non-null  float64
 40  availability_90                               10000 non-null  float64
 41  availability_365                              10000 non-null  object
 42  calendar_last_scraped                         10000 non-null  object
 43  number_of_reviews                             10000 non-null  float64
 44  number_of_reviews_ltm                         10000 non-null  float64
 45  number_of_reviews_l30d                        10000 non-null  float64
 46  first_review                                  7808 non-null   object
 47  last_review                                   7808 non-null   object
 48  review_scores_rating                          7808 non-null   object
 49  review_scores_accuracy                        7796 non-null   float64
 50  review_scores_cleanliness                     7796 non-null   float64
 51  review_scores_checkin                         7794 non-null   float64
 52  review_scores_communication                   7796 non-null   float64
 53  review_scores_location                        7795 non-null   float64
 54  review_scores_value                           7795 non-null   float64
 55  instant_bookable                              9998 non-null   object
 56  calculated_host_listings_count                9998 non-null   float64
 57  calculated_host_listings_count_entire_homes   9998 non-null   float64
 58  calculated_host_listings_count_private_rooms  9998 non-null   float64
 59  calculated_host_listings_count_shared_rooms   9998 non-null   float64
 60  reviews_per_month                             7806 non-null   float64
 61  city                                          9998 non-null   object
dtypes: float64(29), object(33)
memory usage: 4.7+ MB

converting features into there preferable d types

In [6]:

def is_datelike(s, fmt='%Y-%m-%d'):
    try:
        pd.to_datetime(s, format=fmt, errors='raise')
        return True
    except ValueError:
        return False
df['last_scraped'] = pd.to_datetime(df['last_scraped'].apply(lambda x: x if is_datelike(x) else pd.NaT), errors='coerce')
df['host_since'] = pd.to_datetime(df['host_since'], format='%Y-%m-%d', errors='coerce')
df['last_review'] = pd.to_datetime(df['last_review'], format='%Y-%m-%d', errors='coerce')
df.head()

,id,last_scraped,name,description,host_name,host_since,host_location,host_response_time,host_response_rate,host_acceptance_rate,...,review_scores_communication,review_scores_location,review_scores_value,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month,city
0,1000872389527520310,2024-09-04,#10 Modern condo 4B/2.5B,ATTENTION: If you are planing to have a party ...,Wayne,2017-06-25,"Pasadena, CA",within an hour,100%,100%,...,4.72,4.48,4.59,t,13.0,13.0,0.0,0.0,2.85,los_angeles
1,21216996,2024-09-05,Stairway to Los Angeles Views Room andprivate ...,Private Guest rooms in the hills of Los Angele...,Scott & Kim,2016-02-23,"Los Angeles, CA",NaN,NaN,NaN,...,4.81,4.79,4.76,f,2.0,0.0,2.0,0.0,1.01,los_angeles
2,810908225191909546,2024-09-05,Hollywood Hills House with View,This is a Hollywood Hills mid-century modern p...,Louise,2016-08-10,"Los Angeles, CA",within an hour,100%,100%,...,5.00,4.87,4.70,f,1.0,1.0,0.0,0.0,2.48,los_angeles
3,39310458,2024-09-05,"Private Long Beach Rental: 2Bd 1Bth, mins-LBG,...","To future guests,<br /><br />This unique moder...",Francisca,2015-06-02,"Long Beach, CA",within an hour,100%,96%,...,4.88,4.56,4.56,f,1.0,1.0,0.0,0.0,1.72,los_angeles
4,691931631507059313,2024-09-05,LUXURY BEVERLY VILLA!! - PRIME LOCATION!!!,This contemporary smart home lies minutes from...,Diana,2014-07-22,"Santa Monica, CA",within an hour,99%,83%,...,4.80,4.80,4.40,f,63.0,63.0,0.0,0.0,0.22,los_angeles

In [7]:
# Columns to convert
percentage_columns = ['host_response_rate', 'host_acceptance_rate']

for column in percentage_columns:
    try:
        df[column] = df[column].str.rstrip('%').astype(float) / 100
        df[column] = df[column].astype(float)
    except (ValueError, AttributeError):
        print(f"Could not convert column '{column}' to percentage. Skipping...")
# Convert INTO BOOLEAN
for column in ['host_is_superhost', 'host_has_profile_pic', 'host_identity_verified', 'has_availability', 'instant_bookable']:
    df[column] = df[column].map({'t': True, 'f': False}).astype(bool)

# Convert numeric columns, handling potential errors
for column in ['host_listings_count', 'host_total_listings_count', 'minimum_nights', 'maximum_maximum_nights', 'minimum_maximum_nights']:
    df[column] = pd.to_numeric(df[column], errors='coerce').astype('Int64')

# Convert 'price' to float after removing currency symbols
df['price'] = df['price'].astype(str).str.replace('[\$,]', '', regex=True).astype(float)
df.rename(columns={'price': 'price_in_dollar'}, inplace=True)

# Print the updated DataFrame info to check data types
df.info()
df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10002 entries, 0 to 10001
Data columns (total 62 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   id                                            10002 non-null  object
 1   last_scraped                                  10000 non-null  datetime64[ns]
 2   name                                          10002 non-null  object
 3   description                                   9718 non-null   object
 4   host_name                                     10002 non-null  object
 5   host_since                                    10000 non-null  datetime64[ns]
 6   host_location                                 7842 non-null   object
 7   host_response_time                            8422 non-null   object
 8   host_response_rate                            8422 non-null   float64
 9   host_acceptance_rate                          8530 non-null   float64
 10  host_is_superhost                             10002 non-null  bool
 11  host_neighbourhood                            8454 non-null   object
 12  host_listings_count                           9998 non-null   Int64
 13  host_total_listings_count                     10000 non-null  Int64
 14  host_verifications                            9999 non-null   object
 15  host_has_profile_pic                          10002 non-null  bool
 16  host_identity_verified                        10002 non-null  bool
 17  neighbourhood_cleansed                        10000 non-null  object
 18  latitude                                      10000 non-null  float64
 19  longitude                                     10000 non-null  float64
 20  property_type                                 10000 non-null  object
 21  room_type                                     10000 non-null  object
 22  accommodates                                  10000 non-null  float64
 23  bathrooms                                     8599 non-null   float64
 24  bathrooms_text                                9995 non-null   object
 25  bedrooms                                      9538 non-null   float64
 26  beds                                          8578 non-null   float64
 27  amenities                                     10000 non-null  object
 28  price_in_dollar                               8601 non-null   float64
 29  minimum_nights                                9998 non-null   Int64
 30  maximum_nights                                10000 non-null  float64
 31  minimum_minimum_nights                        10000 non-null  float64
 32  maximum_minimum_nights                        10000 non-null  float64
 33  minimum_maximum_nights                        9998 non-null   Int64
 34  maximum_maximum_nights                        9998 non-null   Int64
 35  minimum_nights_avg_ntm                        10000 non-null  float64
 36  maximum_nights_avg_ntm                        10000 non-null  float64
 37  has_availability                              10002 non-null  bool
 38  availability_30                               10000 non-null  float64
 39  availability_60                               10000 non-null  float64
 40  availability_90                               10000 non-null  float64
 41  availability_365                              10000 non-null  object
 42  calendar_last_scraped                         10000 non-null  object
 43  number_of_reviews                             10000 non-null  float64
 44  number_of_reviews_ltm                         10000 non-null  float64
 45  number_of_reviews_l30d                        10000 non-null  float64
 46  first_review                                  7808 non-null   object
 47  last_review                                   7806 non-null   datetime64[ns]
 48  review_scores_rating                          7808 non-null   object
 49  review_scores_accuracy                        7796 non-null   float64
 50  review_scores_cleanliness                     7796 non-null   float64
 51  review_scores_checkin                         7794 non-null   float64
 52  review_scores_communication                   7796 non-null   float64
 53  review_scores_location                        7795 non-null   float64
 54  review_scores_value                           7795 non-null   float64
 55  instant_bookable                              10002 non-null  bool
 56  calculated_host_listings_count                9998 non-null   float64
 57  calculated_host_listings_count_entire_homes   9998 non-null   float64
 58  calculated_host_listings_count_private_rooms  9998 non-null   float64
 59  calculated_host_listings_count_shared_rooms   9998 non-null   float64
 60  reviews_per_month                             7806 non-null   float64
 61  city                                          9998 non-null   object
dtypes: Int64(5), bool(5), datetime64[ns](3), float64(31), object(18)
memory usage: 4.4+ MB

,id,last_scraped,name,description,host_name,host_since,host_location,host_response_time,host_response_rate,host_acceptance_rate,...,review_scores_communication,review_scores_location,review_scores_value,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month,city
0,1000872389527520310,2024-09-04,#10 Modern condo 4B/2.5B,ATTENTION: If you are planing to have a party ...,Wayne,2017-06-25,"Pasadena, CA",within an hour,1.00,1.00,...,4.72,4.48,4.59,True,13.0,13.0,0.0,0.0,2.85,los_angeles
1,21216996,2024-09-05,Stairway to Los Angeles Views Room andprivate ...,Private Guest rooms in the hills of Los Angele...,Scott & Kim,2016-02-23,"Los Angeles, CA",NaN,NaN,NaN,...,4.81,4.79,4.76,False,2.0,0.0,2.0,0.0,1.01,los_angeles
2,810908225191909546,2024-09-05,Hollywood Hills House with View,This is a Hollywood Hills mid-century modern p...,Louise,2016-08-10,"Los Angeles, CA",within an hour,1.00,1.00,...,5.00,4.87,4.70,False,1.0,1.0,0.0,0.0,2.48,los_angeles
3,39310458,2024-09-05,"Private Long Beach Rental: 2Bd 1Bth, mins-LBG,...","To future guests,<br /><br />This unique moder...",Francisca,2015-06-02,"Long Beach, CA",within an hour,1.00,0.96,...,4.88,4.56,4.56,False,1.0,1.0,0.0,0.0,1.72,los_angeles
4,691931631507059313,2024-09-05,LUXURY BEVERLY VILLA!! - PRIME LOCATION!!!,This contemporary smart home lies minutes from...,Diana,2014-07-22,"Santa Monica, CA",within an hour,0.99,0.83,...,4.80,4.80,4.40,False,63.0,63.0,0.0,0.0,0.22,los_angeles

General datacleaning step handling mising values

In [8]:
df['reviews_per_month'] = df['reviews_per_month'].fillna(0)
df['review_scores_checkin'] = df['review_scores_checkin'].fillna(df['review_scores_checkin'].median())
df['review_scores_value'] = df['review_scores_value'].fillna(df['review_scores_value'].median())
df['review_scores_location'] = df['review_scores_value'].fillna(df['review_scores_value'].median())
df['review_scores_communication'] = df['review_scores_value'].fillna(df['review_scores_value'].median())
df['review_scores_cleanliness'] = df['review_scores_value'].fillna(df['review_scores_value'].median())
df['review_scores_accuracy'] = df['review_scores_value'].fillna(df['review_scores_value'].median())
df['review_scores_rating'] = pd.to_numeric(df['review_scores_rating'], errors='coerce')

imputer = KNNImputer(n_neighbors=5)  # Adjust n_neighbors as needed
df['review_scores_rating'] = imputer.fit_transform(df[['review_scores_rating']])[:, 0]
# Replace missing values in 'first_review' with 'host_since'
df['first_review'] = df['first_review'].fillna(df['host_since'])
# Replace missing values in 'last_review' with 'last_scraped'
df['last_review'] = df['last_review'].fillna(df['last_scraped'])
#replacing host location with city
df['host_location'] = df['host_location'].fillna(df['city'])
df['host_response_time'] = df['host_response_time'].fillna(df['host_response_time'].mode()[0])
df['host_response_rate'] = df['host_response_rate'].fillna(df['host_response_rate'].mode()[0])
df['host_neighbourhood'] = df['host_neighbourhood'].fillna('no neighbourhood specified')
df['host_acceptance_rate'] = df['host_acceptance_rate'].fillna(df['host_acceptance_rate'].median())
df['beds'] = df['beds'].fillna(df['beds'].mode()[0])
df['bedrooms'] = df['bedrooms'].fillna(df['bedrooms'].mode()[0])
df['bathrooms'] = df['bathrooms'].fillna(df['bathrooms'].mode()[0])
df['price_in_dollar'] = df['price_in_dollar'].fillna(df['price_in_dollar'].mean())
df['description'] = df['description'].fillna('no Description')
# print(df[df['bathrooms_text'].isnull()])
#after analysis we can observe that row of index 2434 and 4549 have maximum number of missing value
index_to_drop = [2434, 4549]
existing_indices = df.index
index_to_drop = [index for index in index_to_drop if index in existing_indices]
if index_to_drop:
    df.drop(index_to_drop, inplace=True)
df['bathrooms_text'] = df['bathrooms_text'].fillna('unknown')
#droping row where city is null
df = df.dropna(subset=['city'])
round(df.isnull().sum()/len(df)*100,2).sort_values(ascending=False)

id                        0.0
first_review              0.0
minimum_maximum_nights    0.0
maximum_maximum_nights    0.0
minimum_nights_avg_ntm    0.0
                         ...
bedrooms                  0.0
beds                      0.0
amenities                 0.0
price_in_dollar           0.0
city                      0.0
Length: 62, dtype: float64

In [9]:
# Specify the file path and name
file_path = '/content/sample_data/missingvalues_handeled.csv'  # Changed to a file name within the directory

#Convert DataFrame to CSV
df.to_csv(file_path, index=False)